### ISSUE TITLE
How does this compare to Logary?

### ISSUE THREAD

**Issue by Issacss** [enkomio/Fslog#1]
Just curious, since the documentation is fairly sparse - how does Fslog compare to something like [Logary](https://github.com/logary/logary)? Or maybe something like [Serilog](http://serilog.net/) on the C# side?

**Comment by enkomio** [comment]
Hi,

my idea with Fslog is to have a logging framework that is very simple and minimal. The lack of "advanced" features is something that I wanted to avoid but that can be easily implemented with few effort. If you take a look at the code you can see that no third part library are used in the framework (the usage of a third part library strongly couple your code).

I also wanted a logging library that makes use of the semantic logging paradigm (https://msdn.microsoft.com/en-us/library/dn440729(v=pandp.60).aspx).

Finally, I wanted a logging library that wasn't strictly related to the singleton pattern. In most of the examples of the current logging frameworks you can see an abundance of usage of static methods in order to create a logger. If you consider a scenario where you want to create a different logger object for each istance of a given class, with static methods this task is not easily done.

As you said the documentation is still sparse, I hope to write soon a more comprehensive one, also by including part of this question in it ;)
